# Generated by Django 3.2.22 on 2024-02-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sage',
            new_name='stage',
        ),
    ]
